In [1]:
import numpy as np
import torch as torch

In [4]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

print(np.matmul(A, B))
# shotcut
print(A@B)
print(np.round(C.T@A, 2))  # rounds to two digs

[[ 0.97759257 -0.18962814 -1.13807893  6.74255467 -0.05575912]
 [-0.52678157  0.77840637  0.25895325 -1.19631989  0.88694563]
 [ 0.78284821 -1.21984318 -0.70547064  1.52379625 -1.69228918]]
[[ 0.97759257 -0.18962814 -1.13807893  6.74255467 -0.05575912]
 [-0.52678157  0.77840637  0.25895325 -1.19631989  0.88694563]
 [ 0.78284821 -1.21984318 -0.70547064  1.52379625 -1.69228918]]
[[ 4.41  0.93 -2.79  0.7 ]
 [-1.55 -0.03  1.32 -0.06]
 [-3.04 -2.17  0.35 -1.08]
 [-2.49 -1.7   0.27 -1.02]
 [-2.51 -3.28 -1.25 -1.47]
 [-4.24 -1.95  1.83 -0.68]
 [-1.77 -2.47 -1.03 -1.08]]


In [5]:
A = torch.randn(3, 4)  # no submodule for random initialization
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

print(np.round(A@B, 2))  # notice numpy is rounding torch tensor!
print(type(A@B))

# matmul for torch and np
print(np.round(A@C1, 2))  # torch is multiplying with numpy! Not always compatible with each other!

tensor([[ 0.5300, -0.7300, -0.5200,  0.1700, -0.7100],
        [ 0.3400, -1.3300,  0.9300,  2.7200,  0.9100],
        [-0.3400,  0.2900,  0.2000, -1.5100,  0.7100]])
<class 'torch.Tensor'>
tensor([[-1.4100, -2.4200, -3.9200,  0.4500,  0.9500, -0.0400, -3.0900],
        [-0.9900,  1.7500, -2.4100,  2.7700,  0.6700,  0.1000, -0.0500],
        [ 0.2800, -0.8000,  2.2600, -2.5400,  0.3400,  0.2400,  0.0700]],
       dtype=torch.float64)
