In [3]:
import numpy as np
import torch

In [8]:
nv = np.array([[1, 2, 3, 4]])  # to transpose row vector, has to have the transpose dimension, so 2D
print(nv)

[[1 2 3 4]]


In [9]:
print(nv.T)

[[1]
 [2]
 [3]
 [4]]


In [12]:
nM = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])
print(nM)
print(nM.T)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [13]:
tv = torch.tensor([
    [1, 2, 3, 4]
])  # sometimes torch and np work the same (as here), but most often not. 
print(tv.T)

tensor([[1],
        [2],
        [3],
        [4]])


In [16]:
tM = torch.tensor([
    [1, 2, 3, 4], 
    [5, 6, 7, 8]
])
print(tM)
print(tM.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
